### PR TITLE
V20.5.x

### PR DESCRIPTION
**Pull request by mengxin-mx-cpu**
hi,I can not make the code。

[ 96%] Generating ../../../../source/kernel/iotrace.ko
make[4]: Entering directory `/usr/src/kernels/3.10.0-957.el7.x86_64'
  CC [M]  /home/standalone-linux-io-tracer/source/kernel/main.o
In file included from /home/standalone-linux-io-tracer/source/kernel/io_trace.h:10:0,
                 from /home/standalone-linux-io-tracer/source/kernel/context.h:10,
                 from /home/standalone-linux-io-tracer/source/kernel/main.c:10:
/home/standalone-linux-io-tracer/source/kernel/trace.h:1:1: error: expected identifier or ‘(’ before ‘.’ token
 ../../modules/open-cas-telemetry-framework/source/octf/trace/trace.h
 ^
In file included from /home/standalone-linux-io-tracer/source/kernel/io_trace.h:11:0,
                 from /home/standalone-linux-io-tracer/source/kernel/context.h:10,
                 from /home/standalone-linux-io-tracer/source/kernel/main.c:10:
/home/standalone-linux-io-tracer/source/kernel/trace_inode.h:70:26: error: unknown type name ‘octf_trace_t’
                          octf_trace_t trace,

### CODE REVIEW

**Comment by mmkayPL** [comment]
Did you mean this push request to be a bug report? Were you building the 20.5.x branch? Which Linux distribution were you using? I'm assuming the modules/open-cas-telemetry-framework/source/octf/trace/trace.h file is unmodified?

**Comment by mengxin-mx-cpu** [comment]
> Did you mean this push request to be a bug report? Were you building the 20.5.x branch? Which Linux distribution were you using? I'm assuming the modules/open-cas-telemetry-framework/source/octf/trace/trace.h file is unmodified?

---Hi，
I use the gitbash  did the steps(1-4) on windows:
1、git clone https://github.com/Open-CAS/standalone-linux-io-tracer/
2、cd standalone-linux-io-tracer
3、git checkout $(git tag | grep "^v[[:digit:]]*.[[:digit:]]*.[[:digit:]]*$" | tail -1)
4、git submodule update --init --recursive
---then I copy the "standalone-linux-io-tracer" to linux(centos 7.6), and do steps 5/6
5、sudo ./setup_dependencies.sh
6、make

I think the patch is 20.5.x。I want use this tool on Centos 7.6 Linux distribution,but it Compile error.

**Comment by mmkayPL** [comment]
I reproduced the issue on my end It seems like Windows broke some symbolic links, could you recreate them on the Linux end?:
cd source/kernel
rm -f trace.c trace.h procfs_files.h iotrace_event.h
ln -s ../../modules/open-cas-telemetry-framework/source/octf/trace/trace.c trace.c
ln -s ../../modules/open-cas-telemetry-framework/source/octf/trace/trace.h trace.h
ln -s ../includes/procfs_files.h procfs_files.h
ln -s ../../modules/open-cas-telemetry-framework/source/octf/trace/iotrace_event.h iotrace_event.h

**Comment by mengxin-mx-cpu** [comment]
> I reproduced the issue on my end It seems like Windows broke some symbolic links, could you recreate them on the Linux end?:
> cd source/kernel
> rm -f trace.c trace.h procfs_files.h iotrace_event.h
> ln -s ../../modules/open-cas-telemetry-framework/source/octf/trace/trace.c trace.c
> ln -s ../../modules/open-cas-telemetry-framework/source/octf/trace/trace.h trace.h
> ln -s ../includes/procfs_files.h procfs_files.h
> ln -s ../../modules/open-cas-telemetry-framework/source/octf/trace/iotrace_event.h iotrace_event.h

It works.Thank you!
You definitely were a great help！

**Pull request closed without merging**
