### PR TITLE
Tracing filesystem events

### PR DESCRIPTION
**Pull request by tomaszrybicki**
Signed-off-by: Tomasz Rybicki <tomasz.rybicki@intel.com>

### CODE REVIEW

**Comment by tomaszrybicki** [comment]
retest this please

**Comment by tomaszrybicki** [comment]
Maybe (if possible) we should mark not individual inodes but VFS mount?

**Comment by jcurryaz1** [comment]
I am downloading the zip to a USB key and moving them over.  I will try the cloning method today but why the error on the setup dependency for io tracer?

**Comment by tomaszrybicki** [comment]
retest this please

**Comment by tomaszrybicki** [comment]
retest this please

**Comment by mariuszbarczak** [comment]
reset this please

**Pull request merged**
